config/routes.rb
Rails.application.routes.draw do
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  root to: 'home#index'
  resources :buildings
  get 'buy' => 'home#buy'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/building.rb
class Building < ApplicationRecord
    attr_accessor :rooms, :floors
    enum subtype: {house: "house", complex: "complex", commercial: "commercial"}, _suffix: true
    has_one_attached :building_image
    validate :acceptable_image

    def acceptable_image
        return unless building_image.attached?

        unless building_image.byte_size <= 1.megabyte
            errors.add(:building_image, "is too big")
          end
        
          acceptable_types = ["image/jpg", "image/jpeg", "image/png"]
          unless acceptable_types.include?(building_image.content_type)
            errors.add(:building_image, "must be a JPEG or PNG")
          end
    end
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    # Make the current_user method available to views also, not just controllers:
  helper_method :current_user

  # Define the current_user method:
  def current_user
    # Look up the current user based on user_id in the session cookie:
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  
  # authroize method redirects user to login page if not logged in:
  def authorize
    redirect_to login_path, alert: 'You must be logged in to access this page.' if current_user.nil?
  end
end

app/controllers/buildings_controller.rb
class BuildingsController < ApplicationController
  before_action :set_building, only: [:show, :edit, :update, :destroy]
  before_action :authorize
  # GET /buildings
  # GET /buildings.json
  def index
    @buildings = Building.all
  end

  # GET /buildings/1
  # GET /buildings/1.json
  def show
  end

  # GET /buildings/new
  def new
    @building = Building.new
  end

  # GET /buildings/1/edit
  def edit
  end

  # POST /buildings
  # POST /buildings.json
  def create
    @building = Building.new(building_params)

    @building = set_descriptions(@building)

    respond_to do |format|
      if @building.save
        format.html { redirect_to @building, notice: 'Building was successfully created.' }
        format.json { render :show, status: :created, location: @building }
      else
        format.html { render :new }
        format.json { render json: @building.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /buildings/1
  # PATCH/PUT /buildings/1.json
  def update
    respond_to do |format|
      if @building.update(building_params)
        format.html { redirect_to @building, notice: 'Building was successfully updated.' }
        format.json { render :show, status: :ok, location: @building }
      else
        format.html { render :edit }
        format.json { render json: @building.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /buildings/1
  # DELETE /buildings/1.json
  def destroy
    @building.destroy
    respond_to do |format|
      format.html { redirect_to buildings_url, notice: 'Building was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_building
      @building = Building.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def building_params
      params.require(:building).permit(:owner, :address, :sqmt, :price, :subtype, :building_image)
    end

    def set_descriptions(building)
      case building.subtype
      when "house"
        building.description['rooms'] = params['building']['rooms']
        building.description['floors'] = params['building']['floors']
        building.description['air_conditioned'] = params['air_conditioned']
      when "complex"
        building.description['units'] = params['units']
      when "commercial"
        building.description['shops'] = params['shops']
        building.description['parking'] = params['units']
      end
      building
    end

  #   def common_params
  #     [:rooms, :floors]
  #  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @buildings = Building.order(created_at: :desc)
  end

  def buy
    VeryLongTaskJob.perform_later
    redirect_to root_path
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.find_by(email: params[:login][:email].downcase)
    respond_to do |format|
      if @user && @user.authenticate(params[:login][:password])
        # Log the user in and redirect to the user's show page.
        session[:user_id] = @user.id.to_s
        format.html { redirect_to buildings_path, notice: "Successfully Logged in"}
      else
        # Create an error message.
        format.html { render 'new' }
      end
    end
  end

  def destroy
    session[;user_id] = nil
    respond_to do |format|
      format.html { redirect_to buildings_url, notice: 'Building was successfully destroyed.' }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/buildings_helper.rb
module BuildingsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/buildings/_form.html.erb
<div class="container">
  <%= form_with(model: building, local: true) do |form| %>
    <% if building.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(building.errors.count, "error") %> prohibited this building from being saved:</h2>

        <ul>
          <% building.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="row">
      <div class="col-4">
        <fieldset>
              <div class="form-group">
              <%= form.label :owner %>
              <%= form.text_field :owner , class: "form-control", placeholder: "Input Owner"%>
              </div>
        </fieldset>
      </div>

      <div class="col-4">
        <fieldset>
              <div class="form-group">
              <%= form.label :address %>
              <%= form.text_field :address , class: "form-control", placeholder: "Address"%>
              </div>
        </fieldset>
      </div>
      </div>

    <div class="row">
      <div class="col-4">
        <fieldset>
              <div class="form-group">
              <%= form.label :sqmt %>
              <%= form.number_field :sqmt ,min: 1 , class: "form-control", placeholder: "Square Meters"%>
              </div>
        </fieldset>
      </div>

      <div class="col-4">
        <fieldset>
              <div class="form-group">
              <%= form.label :price %>
              <%= form.number_field :price ,min: 1 , class: "form-control", placeholder: "Price"%>
              </div>
        </fieldset>
      </div>
    </div>

    <div class="row">

<div class="col-4">
<fieldset>
    <div class="form-group">
      <%= form.label :subtype %>
      <%= form.select :subtype, Building.subtypes.keys, {}, class: "form-control"%>
    </div>
    </fieldset>
    </div>

      <div class="col-4">
        <fieldset>
              <div class="form-group">
              <%= form.label :building_image %>
              <%= form.file_field :building_image , class: "form-control"%>
              </div>
        </fieldset>
      </div>
    </div>

  <div id="house">

    <div class="row">
      <div class="col-4">
        <fieldset>
              <div class="form-group">
              <%= form.label :rooms %>
              <%= form.number_field :rooms ,min: 1 , class: "form-control", placeholder: "Rooms"%>
              </div>
        </fieldset>
      </div>
    </div>

    <div class="form-group">
      <%= label_tag 'air_conditioned' %>
      <br/>
      <%= radio_button_tag 'air_conditioned', 'Yes', true %>
      <%= label_tag "Yes" %>
      <br/>
      <%= radio_button_tag 'air_conditioned', 'No' %>
      <%= label_tag "No" %>
    </div>

    <div class="row">
        <div class="col-4">
          <fieldset>
                <div class="form-group">
                <%= form.label :floors %>
                <%= form.number_field :floors ,min: 1 , class: "form-control", placeholder: "Floors"%>
                </div>
          </fieldset>
        </div>
      </div>
    </div>

  <div id="complex">
    <div class="row">
      <div class="col-4">
        <fieldset>
          <div class="form-group">
            <%= form.label :units %>
            <%= form.number_field :units ,min: 1 , class: "form-control", placeholder: "Units"%>
          </div>
        </fieldset>
      </div>
    </div>
  </div>

  <div id="commercial">
    <div class="row">
      <div class="col-4">
        <fieldset>
              <div class="form-group">
              <%= form.label :shops %>
              <%= form.number_field :shops ,min: 1 , class: "form-control", placeholder: "Shops"%>
              </div>
        </fieldset>
      </div>
    </div>

    <div class="row">
      <div class="col-4">
        <fieldset>
              <div class="form-group">
              <%= form.label :parking %>
              <%= form.number_field :parking ,min: 1 , class: "form-control", placeholder: "Units"%>
              </div>
        </fieldset>
      </div>
    </div>
  </div>

    <div class="form-group">
      <%= form.submit "SUBMIT", class: "btn btn-primary"%>
    </div>
  <% end %>
</div>

app/views/buildings/edit.html.erb
<h1>Editing Building</h1>

<%= render 'form', building: @building %>

<%= link_to 'Show', @building %> |
<%= link_to 'Back', buildings_path %>

app/views/buildings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Buildings</h1>

<table>
  <thead>
    <tr>
    <th>Image</th>
      <th>Owner</th>
      <th>Address</th>
      <th>Sqmt</th>
      <th>Price</th>
      <th>Type</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @buildings.each do |building| %>
      <tr>
        <td><%= image_tag building.building_image.attached? ? building.building_image : "" ,  size:"100x100"  %></td>
        <td><%= building.owner %></td>
        <td><%= building.address %></td>
        <td><%= building.sqmt %></td>
        <td><%= building.price %></td>
        <td><%= building.subtype %></td>
        <td><%= link_to 'Show', building %></td>
        <td><%= link_to 'Edit', edit_building_path(building) %></td>
        <td><%= link_to 'Destroy', building, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Building', new_building_path %>

app/views/buildings/new.html.erb
<h1>New Building</h1>

<%= render 'form', building: @building %>

<%= link_to 'Back', buildings_path %>

app/views/buildings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Building Image:</strong>
   <%= image_tag @building.building_image.attached? ? @building.building_image : "" ,  size:"100x100"  %>
</p>

<p>
  <strong>Owner:</strong>
  <%= @building.owner %>
</p>

<p>
  <strong>Address:</strong>
  <%= @building.address %>
</p>

<p>
  <strong>Sqmt:</strong>
  <%= @building.sqmt %>
</p>

<p>
  <strong>Price:</strong>
  <%= @building.price %>
</p>

<p>
  <strong>Type:</strong>
  <%= @building.subtype %>
</p>

<% if @building.subtype == "house" %>
  <p>
    <strong>Floor(s):</strong>
    <%= @building.description['rooms'] %>
  </p>
  <p>
    <strong>Air Conditioned:</strong>
    <%= @building.description['air_conditioned'] %>
  </p>
  <p>
    <strong>Room(s):</strong>
    <%= @building.description['rooms'] %>
  </p>
  <% elsif @building.subtype == "complex" %>

  <p>
    <strong>Units:</strong>
    <%= @building.description['units']  %>
  </p>
      
  <% else %>
  <p>
    <strong>Parking:</strong>
    <%= @building.description['parking'] %>
  </p>
  <p>
    <strong>Shops:</strong>
    <%= @building.description['shops'] %>
  </p>
<% end %>

<%= link_to 'Edit', edit_building_path(@building) %> |
<%= link_to 'Back', buildings_path %>

app/views/home/index.html.erb
<p id="notice"><%= notice %></p>
      <div class="page-header" id="banner">
        <div class="row">
          <div class="col-lg-8 col-md-7 col-sm-6">
            <h1>Buildings</h1>
          </div>
          <div class="col-lg-4 col-md-5 col-sm-6">
                <%= link_to "ADD PROPERTY", buildings_path%>
          </div>
        </div>
      </div>


        <% @buildings.each do |building| %>

        <div class="row">
          <div class="col-lg-10 col-md-7 col-sm-6">
                <div class="card border-secondary mb-3">
                <div class="card-body">
                    <div class="row">
                        <div class="col-3">
                            <%= image_tag building.building_image.attached? ? building.building_image : "" ,  size:"100x100"  %>
                        </div>
                        <div class="col-8 mx-auto">
                            <div class="row">
                                <div class="col-4">
                                    <p class="card-text"><b>Owner: </b><%= building.owner %></p>
                                </div>
                                <div class="col-4">
                                    <p class="card-text"><b>Address: </b><%= building.address %></p>
                                </div>
                                <div class="col-4">
                                    <p class="card-text"><b>Price: </b><%= building.price %></p>
                                </div>
                            </div>

                            <div class="row">
                                <div class="col-4">
                                    <p class="card-text"><b>SQ Meter: </b><%= building.sqmt %></p>
                                </div>
                                <div class="col-4">
                                    <p class="card-text"><b>Price: </b><%= building.price %></p>
                                </div>
                                <div class="col-4">
                                    <p class="card-text"><b>Building Type: </b><%= building.subtype %></p>
                                </div>
                            </div>

                            <div class="row">
                            <% if building.subtype == "house" %>
                                <div class="col-4">
                                    <p class="card-text"><b>Floor(s): </b><%= building.description['floors'] %></p>
                                </div>
                                <div class="col-4">
                                    <p class="card-text"><b>Air Conditioned: </b><%= building.description['air_conditioned'] %></p>
                                </div>
                                <div class="col-4">
                                    <p class="card-text"><b>Room(s): </b><%= building.description['rooms'] %></p>
                                </div>
                            
                            <% elsif building.subtype == "complex" %>
                                <div class="col-4">
                                    <p class="card-text"><b>Units: </b><%= building.description['units'] %></p>
                                </div>
                            <% else %>
                                <div class="col-4">
                                    <p class="card-text"><b>Parking: </b><%= building.description['parking']  %></p>
                                </div>
                                <div class="col-4">
                                    <p class="card-text"><b>Shops: </b><%= building.description['shops'] %></p>
                                </div>
                            <% end %>
                            </div>
                            <div class="row justify-center">
                                <div class="col-4 offset-4">
                                <p><%= time_ago_in_words(building.created_at) %> ago</p>
                                </div>
                            </div>
                        </div>
                        <div class="col-1">
                            <%= link_to "BUY" , buy_path, class: "btn btn-primary" %>
                        </div>
                    </div>
                </div>
                </div>
          </div>
        </div>
    <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Assetmanagement</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container text-center">
      <%= yield %>
    </div>
  </body>
</html>